resources:
  - https://github.com/kubernetes-sigs/metrics-server/releases/download/v0.7.2/components.yaml

patches:
  - path: kubelet-insecure-tls-patch.yaml
    target:
      kind: Deployment
      name: metrics-server